# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor_1 = torch.rand(7,7)
tensor_1

tensor([[0.0047, 0.2229, 0.5625, 0.5196, 0.3239, 0.3558, 0.2527],
        [0.6140, 0.0197, 0.7779, 0.1320, 0.0119, 0.6090, 0.1190],
        [0.8044, 0.4871, 0.0143, 0.5799, 0.6382, 0.9685, 0.3775],
        [0.8428, 0.9890, 0.8321, 0.2118, 0.2733, 0.0326, 0.2867],
        [0.6584, 0.2217, 0.9471, 0.5375, 0.6734, 0.1112, 0.9070],
        [0.7221, 0.4515, 0.6138, 0.5569, 0.2020, 0.3518, 0.0254],
        [0.4595, 0.4070, 0.2938, 0.6586, 0.0399, 0.6672, 0.3896]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor_2 = torch.rand(1,7)
# Perform matrix multiplication
torch.mm(tensor_1, tensor_2.T)

tensor([[1.1342],
        [1.1138],
        [1.2908],
        [1.6717],
        [1.8967],
        [1.5593],
        [1.2393]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
torch_A = torch.rand(7,7)
torch_B = torch.rand(1,7)

# Matrix multiply tensors
torch.mm(torch_A, torch_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
torch_gpu_one = torch.rand(2,3, device="gpu")
torch_gpu_two = torch.rand(2,3, device="gpu")


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
torch_gpu_result = torch.mm(torch_gpu_one, torch_gpu_two.T)

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
torch.max(torch_gpu_result)
# Find min
torch.min(torch_gpu_result)

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
torch.argmax(torch_gpu_result)

# Find arg min
torch.argmin(torch_gpu_result)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [6]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a_tensor = torch.rand(1,1,1,10)

# Remove single dimensions
a_tensor_s = a_tensor.squeeze()

# Print out tensors and their shapes
print(a_tensor)
print(a_tensor_s, a_tensor_s.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
